[package]
name = "spl-interface-instruction-syn"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.59"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }
