[package]
name = "spl-interface-instructions-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
spl-interface-instructions-syn = { version = "0.1.0", path = "../syn" }
syn = { version = "1.0", features = ["extra-traits"] }