[package]
name = "spl-interface-instruction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.14.12"
spl-interface-instruction-derive = { version = "0.1.0", path = "./derive" }